db:
  url: "jdbc:mysql://localhost:30006/performance_analyze"
  username: "root"
  password: "root"
  driver: "com.mysql.cj.jdbc.Driver"
github:
  owner:
    name: "OWNER_NAME"
    repos:
  token: "<TOKEN>"
jira:
  token: "<TOKEN>"
  url : "https://xxxx.atlassian.net"