db:
  url: "jdbc:mysql://localhost:30006/performance_analyze"
  username: "root"
  password: "root"
  idleTimeout: 60000
  maximumPoolSize: 1
  driverClassName: "com.mysql.cj.jdbc.Driver"
github:
  basePath: "https://api.github.com"
  owner:
    name: "OWNER_NAME"
    repos:
  token: "<TOKEN>"
jiras:
  -
    url: "https://xxx.atlassian.net"
    username: ""
    token: ""
  -
    url: "https://<self-hosted-jira>.com.cn"
    username: ""
    token: ""