apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  type: NodePort
  ports:
  - name: rpc
    port: 6123
    nodePort: 30083
  - name: blob-server
    port: 6124
    nodePort: 30082
  - name: webui
    port: 8081
    nodePort: 30084
  selector:
    app: flink
    component: jobmanager