name: Code Review

permissions: write-all

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: xiaoquisme/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: Chinese
          top_p: 1
          temperature: 1
